[package]
name = "messagechains"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.17"
sha2 = "0.10.6"
js-sys = "0.3.6"
wasm-bindgen = "0.2.83"
hex = "0.4.3"
