- name: Create build and benchmark user
  ansible.builtin.user:
    name: localuser
    comment: Local user with ephemeral home directory
    uid: 500
    group: 2793
    groups: root
    shell: /bin/bash
    create_home: true
    home: /mydata/localuser

- name: Download PyopenSSL 
  become: yes
  become_user: root
  get_url:
    url: https://files.pythonhosted.org/packages/00/3f/ea5cfb789dddb327e6d2cf9377c36d9d8607af85530af0e7001165587ae7/pyOpenSSL-22.1.0-py3-none-any.whl
    dest: /root/pyOpenSSL-22.1.0-py3-none-any.whl
  
- name: Install pyOpenSSL
  become: yes
  become_user: root
  shell: |
    python3 -m easy_install /root/pyOpenSSL-22.1.0-py3-none-any.whl


- name: Ensure the ACL package is installed for Ansible to be able to become the localuser
  become: yes
  become_user: root
  apt:
    name: acl
    state: present
    update_cache: yes
